### ISSUE TITLE
util.hpp error wit C++17 standard

### ISSUE THREAD

**Issue by saeitsystems** [igagis/utki#6]
With building our application with C++17 standard I found two statements, the compiler refused to translate.
1.)
class ScopeExit{
       std::function<void()noexcept> mf; // ERROR
       std::function<void()> mf; // workes fine

2.)

![error](https://user-images.githubusercontent.com/25054917/38877514-1e9f92ce-425f-11e8-8ba3-0edb0cdb4f0a.png)

**Comment by igagis** [comment]
Fixed in version **1.1.16**

**Comment by saeitsystems** [comment]
Thank you for your very fast response!! Weekend hasn't even begun!
I will check it and close the issue later today.

**Comment by saeitsystems** [comment]
Everything compiles fine now!

Another thing which irritated me was the f(std::move(f)) statement. The parameter f is moved to the member f .... It workes but looks confusing and makes it more difficult to understand the code.

**Comment by igagis** [comment]
Ok, thanks for letting me know.
Regarding the `move` statement, I don't see a conceptual reason to copy `std::function` obejct, so I used r-value reference to avoid possible bugs.

**Comment by igagis** [comment]
ah, I see :). I will change it next time I touch the code.
