### ISSUE TITLE
add a printf-like function producing an std::string object

### ISSUE THREAD

**Issue by ilyad** [igagis/utki#8]
Usage example:

```
int a=5;
double x=6.789;
std::string s="foo"
std::string printout=utki::sprintf("a=%d, x=%.2f, s='%s'", a, b, s.c_str());
// The string printout is now "a=5, x=6.79, s='foo'"
```

Note: the function should produce the usual warnings about wrong printf format string, where such are available.

**Comment by igagis** [comment]
Done. Added `make_string()` and `<utki/string.hpp>` in version **1.1.46**.

**Comment by ilyad** [comment]
Great! It would be very nice to have a "v-" version accepting steck pointer instead of argument list as well, similar to vprintf for printf, vsnprintf for snprintf, vfprintf for fprintf etc.

**Comment by igagis** [comment]
Looks like it is not possible due to that we call internally `snprintf` two times. So, after the first call the `va_list` remains in some unusable state and using it the second time does not produce correct result.

**Comment by igagis** [comment]
done in version **1.1.52**
